stages:
  - build
  - linter
  - test
  - deploy

variables:
  SERVER_DIR: "pptpd_admin"

testing:
  stage: test
  tags:
    - test
  image: python:3.10
  before_script:
  - pip3 install toml
  - python3 converter.py -p $SERVER_DIR
  - pip3 install -r $SERVER_DIR/requirements.txt
  script:
    - uvicorn $SERVER_DIR.main:app --host 0.0.0.0 --port 8000 --workers 2 --reload
  only:
    - main

linting:
  stage: linter
  tags: 
    - linter
  image: python:3.10
  before_script:
    - pip3 install toml
    - python3 converter.py -p . -f dev
    - pip3 install -r requirements.txt
  script:
    - flake8 pptpd_admin/*.py
    - mypy pptpd_admin/*.py
  only:
    - main
