stages:
  - build
  - test
  - deploy

variables:
  SERVER_DIR: "pptpd_admin"

linting:
  stage: linter
  tags: 
    - test
  image: python:3.10
  before_script:
    - pip3 install toml
    - python3 converter.py -p . -f dev
    - pip3 install -r requirements.txt
  script:
    - flake8 $SERVER_DIR/
    - mypy $SERVER_DIR/
  only:
    - main

testing:
  stage: test
  tags:
    - test
  image: python:3.10
  before_script:
  - pip3 install pytest
  script:
    - pytest tests/
  only:
    - main
