stages:
  - build
  - linter
  - test
  - deploy

variables:
  SERVER_DIR: "pptpd_admin/"

building-backend:
  stage: build
  tags:
   - build
  image: ubuntu:20.04
  before_script:
    # - cp -r pptpd_admin /
    # - cp init_server.sh /
    - bash init_server.sh
  script:
    - python3 converter.py -p $SERVER_DIR
    - cd pptpd_admin/ && docker build . -t test-image

  only:
    - main

linting:
  stage: linter
  tags: 
    - linter
  image: python:3.10
  before_script:
    - pip3 install toml
    - python3 converter.py -p . -f dev
    - pip3 install -r requirements.txt
    # - cp setup.cfg /
  script:
    - flake8 pptpd_admin/*.py
    - mypy pptpd_admin/*.py
  only:
    - main