stages:
  - build
  - linter
  - test
  - deploy

building-backend:
  stage: build
  tags:
   - build
  image: ubuntu:20.04
  before-script:
    - cp -r pptpd_admin /
    - cp init_server.sh /
    - bash init_server.sh
  script:
    - python3 converter.py
    # - cd pptpd_admin/ && docker build . -t test-image
  only:
    - main

linting:
  stage: linter
  tags: 
    - linter
  image: python:3.10
  script:
    - pip install flake8 flake8-builtins flake8-docstrings flake8-quotes
    - cp setup.cfg /
    - flake8 pptpd_admin/
  only:
    - main