stages:
  - build
  - linter
  - test
  - deploy

building:
  stage: build
  tags:
   - build
  image: ubuntu20.04
  script:
    - python3 converter.py
  only:
    - main

linting:
  stage: linter
  tags: 
    - linter
  image: python:3.10
  script:
    - pip install flake8 flake8-builtins flake8-docstrings flake8-quotes
    - cp setup.cfg /
    - flake8 pptpd_admin/
  only:
    - main