version: '3.8'

services:
  server:
    container_name: FastAPI
    build:
      context: ./pptpd_admin
      dockerfile: build.Dockerfile
      args:
        - p=8000
    ports:
      - 8000:8000
    volumes:
      - /etc/ppp/:/etc/ppp/
    restart: always
  
  web:
    container_name: Vue
    build:
      context: ./vue
    ports:
      - 5173:5173
    restart: always
    depends_on:
      - server
