version: '3.8'

services:
  server:
    container_name: FastAPI
    build:
      context: ./pptpd_admin
      args:
        - p=8000
    ports:
      - 8000:8000
    volumes:
      - /etc/ppp/:/etc/ppp/
    restart: always
  
  web:
    container_name: Web
    build:
      context: ./vue
      args:
        - server_ip=localhost
    ports:
      - 80:80
    restart: always
    depends_on:
      - server
